# -*- coding: utf-8 -*-
"""caps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuvS7TZVjwGPKTS8K-kqpOUAkEY72Dmz
"""

#import library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

#membaca dataset
df = pd.read_csv('/content/ObesityDataSet.csv')

#menampilkan dataset
df.head()